-- 코드를 작성해주세요
SELECT THREE.ID AS ID

FROM ECOLI_DATA ONE

LEFT JOIN ECOLI_DATA AS TWO 

ON ONE.ID = TWO.PARENT_ID

LEFT JOIN ECOLI_DATA AS THREE

ON TWO.ID = THREE.PARENT_ID

WHERE ONE.PARENT_ID IS NULL AND THREE.ID IS NOT NULL

ORDER BY ID;
# 3세대의 대장균의 ID(ID) 를 출력