SELECT YEAR(OS.SALES_DATE) as YEAR, MONTH(OS.SALES_DATE) as MONTH, UI.GENDER, COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM ONLINE_SALE OS
JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, UI.GENDER
ORDER BY YEAR ASC, MONTH ASC, UI.GENDER ASC;

# SELECT * FROM USER_INFO;

# 년, 월, 성별 별로 상품을 구매한 회원수를 집계