-- 코드를 작성해주세요
SELECT COUNT(FI.ID) AS FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_NAME
ORDER BY FISH_COUNT DESC;
#물고기의 종류 별 물고기의 이름과 잡은 수를 출력