-- 코드를 입력하세요
SELECT
CONCAT('/home/grep/src/',
       B.BOARD_ID, '/',
       F.FILE_ID,
       F.FILE_NAME,
       F.FILE_EXT
      ) AS FILE_PATH
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;


#FILE_PATH
#조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로를 조회
