-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(COALESCE(LENGTH, 10)) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(COALESCE(LENGTH,10)) >= 33
ORDER BY FISH_TYPE ASC;

# SELECT * FROM FISH_INFO;

#평균 길이가 33cm 이상인 물고기들을 종류별로 분류하여 잡은 수, 최대 길이, 물고기의 종류를 출력
#FISH_COUNT	MAX_LENGTH	FISH_TYPE